import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
  sectionTitle: { fontSize: 16, fontWeight: '800', color: '#333' },
  dateInfo: { backgroundColor: '#f5f7fa', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 15 },
  dateInfoText: { fontSize: 13, color: '#666' },

  previewSection: { backgroundColor: '#fff', borderRadius: 10, padding: 12, marginBottom: 12, shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 6, shadowOffset: { width: 0, height: 2 } },
  previewContainer: { position: 'relative', width: '100%', height: 200, borderRadius: 10, overflow: 'hidden', backgroundColor: '#667eea' },
  previewContainerEmpty: { position: 'relative', width: '100%', height: 200, borderRadius: 10, overflow: 'hidden', backgroundColor: '#667eea', alignItems: 'center', justifyContent: 'center' },
  previewSlide: { position: 'absolute', width: '100%', height: '100%', display: 'none', alignItems: 'center', justifyContent: 'center' },
  previewSlideActive: { display: 'flex' },
  previewImage: { position: 'absolute', width: '100%', height: '100%', resizeMode: 'cover' },
  previewContent: { zIndex: 2, paddingHorizontal: 20, alignItems: 'center' },
  previewTitle: { fontSize: 18, fontWeight: '800', color: '#fff', marginBottom: 8 },
  previewDesc: { fontSize: 14, color: '#fff', marginBottom: 12 },
  previewButton: { backgroundColor: 'rgba(255,255,255,0.9)', borderRadius: 20, paddingVertical: 8, paddingHorizontal: 20 },
  previewButtonText: { color: '#333', fontSize: 14, fontWeight: '600' },
  previewDots: { position: 'absolute', bottom: 10, left: 0, right: 0, flexDirection: 'row', gap: 6, justifyContent: 'center' },
  previewDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: 'rgba(255,255,255,0.5)' },
  previewDotActive: { backgroundColor: '#fff' },

  calendarSection: { backgroundColor: '#fff', borderRadius: 10, padding: 12, marginBottom: 12, shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 6, shadowOffset: { width: 0, height: 2 } },
  calendarHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
  calendarTitle: { fontSize: 16, fontWeight: '800', color: '#333' },
  weekHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  weekDay: { flex: 1, textAlign: 'center', fontSize: 12, color: '#666' },
  calendarGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  calendarDay: { width: `${100 / 7}%`, aspectRatio: 1, alignItems: 'center', justifyContent: 'center', borderRadius: 8, marginBottom: 4, position: 'relative' },
  calendarDayText: { fontSize: 13, color: '#333' },
  calendarDayOther: { opacity: 0.4 },
  calendarDaySelected: { backgroundColor: '#4a6bdf' },
  calendarDayToday: { borderWidth: 1, borderColor: '#1976d2' },
  bannerIndicator: { position: 'absolute', bottom: 4, width: 6, height: 6, borderRadius: 3, backgroundColor: '#4caf50' },

  bannerSection: { backgroundColor: '#fff', borderRadius: 10, padding: 12, marginBottom: 12, shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 6, shadowOffset: { width: 0, height: 2 } },
  bannerSlots: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  slotCard: { width: '48%', borderWidth: 2, borderColor: '#ddd', borderStyle: 'dashed', borderRadius: 10, padding: 12, minHeight: 200, backgroundColor: '#fafafa' },
  slotHasContent: { borderColor: '#4a6bdf', backgroundColor: '#fff', borderStyle: 'solid' },
  slotEmpty: { borderColor: '#ddd', backgroundColor: '#fafafa' },
  slotHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 },
  slotNumber: { fontWeight: '800', color: '#4a6bdf' },
  slotActions: { flexDirection: 'row', gap: 10 },
  bannerPreview: { width: '100%', height: 120, backgroundColor: '#f0f2f5', borderRadius: 8, alignItems: 'center', justifyContent: 'center', marginBottom: 8, overflow: 'hidden' },
  bannerImage: { width: '100%', height: '100%', resizeMode: 'cover' },
  emptyBanner: { alignItems: 'center', justifyContent: 'center' },
  bannerInfo: { },
  bannerTitle: { fontWeight: '800', color: '#333' },
  bannerPeriod: { fontSize: 12, color: '#888' },

  addButton: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#4a6bdf', borderRadius: 20, paddingVertical: 8, paddingHorizontal: 12 },
  addButtonText: { color: '#fff', fontWeight: '700' },

  // 모달
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', alignItems: 'center', justifyContent: 'center' },
  modalContent: { backgroundColor: '#fff', borderRadius: 10, width: '90%', maxWidth: 600, maxHeight: '80%', padding: 16 },
  modalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
  modalTitle: { fontSize: 18, fontWeight: '800', color: '#333' },
  formGroup: { marginBottom: 12 },
  formLabel: { fontSize: 14, fontWeight: '600', marginBottom: 6, color: '#333' },
  input: { borderWidth: 1, borderColor: '#ddd', borderRadius: 6, paddingHorizontal: 10, height: 40, fontSize: 14 },
  imagePreview: { width: '100%', height: 200, resizeMode: 'cover', borderRadius: 8, marginTop: 10 },
  chip: { backgroundColor: '#f0f2f5', paddingVertical: 6, paddingHorizontal: 12, borderRadius: 15 },
  chipActive: { backgroundColor: '#4a6bdf' },
  chipText: { fontSize: 13, color: '#333' },
  formActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, marginTop: 12 },
  btnPrimary: { backgroundColor: '#4a6bdf', borderRadius: 6, paddingVertical: 10, paddingHorizontal: 14 },
  btnPrimaryText: { color: '#fff', fontSize: 14, fontWeight: '700' },
  btnSecondary: { backgroundColor: '#e0e6ed', borderRadius: 6, paddingVertical: 10, paddingHorizontal: 14 },
  btnSecondaryText: { color: '#333', fontSize: 14, fontWeight: '700' },

  toast: { position: 'absolute', bottom: 20, left: 0, right: 0, alignItems: 'center' },
});

export default styles;
