
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  appHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
    height: 50,
  },
  headerIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  appTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
  },
  headerIcons: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#ff4757',
    width: 16,
    height: 16,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeText: { color: '#fff', fontSize: 10, fontWeight: 'bold' },

  tabNav: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  tabButton: {
    flex: 1,
    minWidth: 65,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
  },
  tabButtonActive: {},
  tabButtonText: { color: '#666', fontSize: 11, marginTop: 3 },
  tabButtonTextActive: { color: '#4a6fdc', fontWeight: 'bold' },
  tabUnderline: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: '#4a6fdc',
  },

  container: {
    paddingHorizontal: 8,
    paddingBottom: 10,
  },

  searchFilterSection: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 12,
    marginTop: 10,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  searchBox: { position: 'relative', marginBottom: 10 },
  searchInput: {
    width: '100%',
    paddingVertical: 8,
    paddingHorizontal: 12,
    paddingRight: 35,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 20,
    fontSize: 13,
  },
  searchIcon: { position: 'absolute', right: 12, top: 12 },
  filterButtons: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  filterBtn: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#ddd',
    backgroundColor: '#fff',
    borderRadius: 15,
    marginRight: 6,
    marginBottom: 6,
  },
  filterBtnActive: { backgroundColor: '#4a6fdc', borderColor: '#4a6fdc' },
  filterBtnText: { fontSize: 11, color: '#666' },
  filterBtnTextActive: { color: '#fff' },

  card: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 8 },

  // Job styles
  jobCard: { borderLeftWidth: 3 },
  jobCompany: { fontSize: 13, fontWeight: 'bold', color: '#333', marginBottom: 3 },
  jobTitle: { fontSize: 14, fontWeight: 'bold', color: '#4a6fdc', marginBottom: 3 },
  jobLocation: { fontSize: 11, color: '#666', marginBottom: 5 },
  jobDate: { fontSize: 10, color: '#999' },
  bookmarkBtn: { padding: 6, borderRadius: 4, alignItems: 'center', justifyContent: 'center' },
  jobTags: { flexDirection: 'row', flexWrap: 'wrap', gap: 4, marginBottom: 8 },
  jobTag: { paddingVertical: 2, paddingHorizontal: 6, backgroundColor: '#e7f1ff', borderRadius: 10 },
  jobTagText: { fontSize: 9, color: '#4a6fdc' },
  jobSalary: { fontSize: 12, fontWeight: 'bold', color: '#28a745', marginBottom: 8 },
  jobActions: { flexDirection: 'row', gap: 6 },
  jobActionBtn: { flex: 1, padding: 6, borderRadius: 4, alignItems: 'center', justifyContent: 'center', flexDirection: 'row' },
  jobActionText: { color: '#fff', fontSize: 11, fontWeight: '500', marginLeft: 4 },
  btnApply: { backgroundColor: '#4a6fdc' },
  btnView: { backgroundColor: '#6c757d' },

  // Education styles
  educationCard: {},
  educationTitle: { fontSize: 14, fontWeight: 'bold', color: '#333', marginBottom: 3 },
  educationOrganizer: { fontSize: 11, color: '#666', marginBottom: 3 },
  educationDate: { fontSize: 10, color: '#999' },
  educationType: { paddingVertical: 3, paddingHorizontal: 6, borderRadius: 10 },
  educationTypeText: { fontSize: 9, fontWeight: '500', color: '#333' },
  // Added types used by Exam tab badges
  typeCertification: { backgroundColor: '#d1ecf1' },
  typeEducation: { backgroundColor: '#fff3cd' },
  typeTraining: { backgroundColor: '#d1ecf1' },
  typeSeminar: { backgroundColor: '#fff3cd' },
  typeWebinar: { backgroundColor: '#d4edda' },
  educationContent: { fontSize: 11, color: '#555', lineHeight: 18, marginBottom: 8 },
  educationInfo: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  educationPrice: { fontWeight: 'bold', color: '#dc3545' },

  // Government styles
  policyCard: { borderLeftWidth: 3 },
  policyTitle: { fontSize: 14, fontWeight: 'bold', color: '#333', marginBottom: 3 },
  policySource: { fontSize: 11, color: '#666', marginBottom: 3 },
  policyDate: { fontSize: 10, color: '#999' },
  policyCategory: { paddingVertical: 3, paddingHorizontal: 6, borderRadius: 10 },
  categoryPolicy: { backgroundColor: '#d1ecf1' },
  categoryNews: { backgroundColor: '#f8d7da' },
  categoryFunding: { backgroundColor: '#d4edda' },
  policyContent: { fontSize: 11, color: '#555', lineHeight: 18, marginBottom: 8 },
  policyTags: { flexDirection: 'row', flexWrap: 'wrap', gap: 4, marginBottom: 8 },
  policyTag: { paddingVertical: 2, paddingHorizontal: 6, backgroundColor: '#e7f1ff', borderRadius: 10 },

  // Exam styles
  examCard: { borderLeftWidth: 3 },
  examTitle: { fontSize: 14, fontWeight: 'bold', color: '#333', marginBottom: 3 },
  examOrganizer: { fontSize: 11, color: '#666', marginBottom: 3 },
  examDate: { fontSize: 10, color: '#999' },
  examType: { paddingVertical: 3, paddingHorizontal: 6, borderRadius: 10 },
  examDetails: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8, alignItems: 'center' },
  examFee: { fontWeight: 'bold', color: '#dc3545' },
  examStatus: { paddingVertical: 2, paddingHorizontal: 6, borderRadius: 10 },
  statusOpen: { backgroundColor: '#d4edda' },
  statusClosed: { backgroundColor: '#f8d7da' },
  statusUpcoming: { backgroundColor: '#fff3cd' },

  // Empty state
  emptyState: { alignItems: 'center', paddingVertical: 40 },
  emptyText: { fontSize: 12, color: '#999', marginTop: 10 },
});