
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#f8f9fa' },
  appHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
    height: 50,
  },
  headerIcon: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  appTitle: { fontSize: 16, fontWeight: 'bold', color: '#333' },
  headerIcons: { position: 'relative', alignItems: 'center', justifyContent: 'center' },
  notificationBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#ff4757',
    width: 16,
    height: 16,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeText: { color: '#fff', fontSize: 10, fontWeight: 'bold' },

  tabNav: { flexDirection: 'row', backgroundColor: '#fff', borderBottomWidth: 1, borderBottomColor: '#eee' },
  tabButton: { flex: 1, minWidth: 70, alignItems: 'center', justifyContent: 'center', paddingVertical: 10 },
  tabButtonActive: {},
  tabButtonText: { color: '#666', fontSize: 12, marginTop: 3 },
  tabButtonTextActive: { color: '#4a6fdc', fontWeight: 'bold' },
  tabUnderline: { position: 'absolute', bottom: 0, left: 0, right: 0, height: 2, backgroundColor: '#4a6fdc' },

  container: { paddingHorizontal: 8, paddingBottom: 10 },

  searchFilterSection: { backgroundColor: '#fff', borderRadius: 8, padding: 12, marginTop: 10, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 3, elevation: 1 },
  searchBox: { position: 'relative', marginBottom: 10 },
  searchInput: { width: '100%', paddingVertical: 8, paddingHorizontal: 12, paddingRight: 35, borderWidth: 1, borderColor: '#ddd', borderRadius: 20, fontSize: 13 },
  searchIcon: { position: 'absolute', right: 12, top: 12 },
  filterButtons: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  filterBtn: { paddingVertical: 5, paddingHorizontal: 10, borderWidth: 1, borderColor: '#ddd', backgroundColor: '#fff', borderRadius: 15, marginRight: 6, marginBottom: 6 },
  filterBtnActive: { backgroundColor: '#4a6fdc', borderColor: '#4a6fdc' },
  filterBtnText: { fontSize: 11, color: '#666' },
  filterBtnTextActive: { color: '#fff' },

  card: { backgroundColor: '#fff', borderRadius: 8, padding: 12, marginBottom: 8, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 3, elevation: 1 },

  // Expert styles
  expertCard: {},
  expertHeader: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 10 },
  expertAvatar: { width: 50, height: 50, borderRadius: 25, backgroundColor: '#f0f0f0', alignItems: 'center', justifyContent: 'center', marginRight: 10, borderWidth: 2, borderColor: '#4a6fdc' },
  expertInfo: { flex: 1 },
  expertName: { fontSize: 14, fontWeight: 'bold', color: '#333', marginBottom: 2 },
  expertTitle: { fontSize: 12, color: '#4a6fdc', fontWeight: '500', marginBottom: 3 },
  expertRating: { flexDirection: 'row', alignItems: 'center', marginBottom: 2 },
  stars: { flexDirection: 'row', marginRight: 5 },
  ratingText: { fontSize: 10, color: '#666' },
  bookmarkBtn: { padding: 6, borderRadius: 4, alignItems: 'center', justifyContent: 'center' },
  expertDetails: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  expertTags: { flexDirection: 'row', flexWrap: 'wrap', gap: 4, marginBottom: 8 },
  expertTag: { paddingVertical: 2, paddingHorizontal: 6, backgroundColor: '#e7f1ff', borderRadius: 10 },
  expertTagText: { fontSize: 9, color: '#4a6fdc' },
  expertActions: { flexDirection: 'row', gap: 6 },
  expertActionBtn: { flex: 1, padding: 6, borderRadius: 4, alignItems: 'center', justifyContent: 'center', flexDirection: 'row' },
  expertActionText: { color: '#fff', fontSize: 11, fontWeight: '500', marginLeft: 4 },
  btnView: { backgroundColor: '#4a6fdc' },
  btnContact: { backgroundColor: '#28a745' },

  // Personnel styles
  personnelCard: {},
  personnelHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 8 },
  personnelName: { fontSize: 14, fontWeight: 'bold', color: '#333', marginBottom: 2 },
  personnelPosition: { fontSize: 12, color: '#666', marginBottom: 3 },
  applicationInfo: { fontSize: 10, color: '#999' },
  personnelSkills: { flexDirection: 'row', flexWrap: 'wrap', gap: 4, marginBottom: 8 },
  skillTag: { paddingVertical: 2, paddingHorizontal: 6, backgroundColor: '#f0f0f0', borderRadius: 10 },
  skillTagText: { fontSize: 9, color: '#666' },

  // Project styles
  projectCard: { borderLeftWidth: 3 },
  projectHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 8 },
  projectTitle: { fontSize: 13, fontWeight: 'bold', color: '#333', marginBottom: 3 },
  projectOrg: { fontSize: 11, color: '#666', marginBottom: 2 },
  projectDate: { fontSize: 9, color: '#999' },
  projectType: { paddingVertical: 3, paddingHorizontal: 6, borderRadius: 10 },
  projectTypeText: { fontSize: 9, fontWeight: '500', color: '#333' },
  categorySupport: { backgroundColor: '#d1ecf1' },
  categoryLaw: { backgroundColor: '#f8d7da' },
  projectContent: { fontSize: 11, color: '#555', lineHeight: 18, marginBottom: 8 },
  projectTags: { flexDirection: 'row', flexWrap: 'wrap', gap: 4, marginBottom: 8 },
  projectTag: { paddingVertical: 2, paddingHorizontal: 6, backgroundColor: '#e7f1ff', borderRadius: 10 },
  projectTagText: { fontSize: 9, color: '#4a6fdc' },
  projectActions: { flexDirection: 'row', gap: 6 },
  projectActionBtn: { flex: 1, padding: 6, borderRadius: 4, alignItems: 'center', justifyContent: 'center', flexDirection: 'row' },
  projectActionText: { color: '#fff', fontSize: 11, fontWeight: '500', marginLeft: 4 },
  btnDetail: { backgroundColor: '#4a6fdc' },
  btnRemove: { backgroundColor: '#dc3545' },

  // Empty state
  emptyState: { alignItems: 'center', paddingVertical: 40 },
  emptyText: { fontSize: 12, color: '#999', marginTop: 10 },
});