import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: { backgroundColor: '#f8f9fa' },
  header: {
    height: 60,
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  headerIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: { fontSize: 18, fontWeight: '700', color: '#333' },
  container: { padding: 16 },

  // 광고/프로필 스타일
  adView: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 2 },
  },
  adHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: '#4a6fdc',
    marginBottom: 12,
  },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: '#333' },
  adStatus: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 20 },
  adStatusText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  statusRunning: { backgroundColor: '#28a745' },
  statusPaused: { backgroundColor: '#ffc107' },
  statusStopped: { backgroundColor: '#dc3545' },

  adProfile: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 12 },
  adAvatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#e7f1ff',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
    borderWidth: 3,
    borderColor: '#4a6fdc',
  },
  adName: { fontSize: 20, fontWeight: '800', color: '#333' },
  adTitle: { fontSize: 14, color: '#4a6fdc', fontWeight: '600', marginTop: 4 },
  adRating: { flexDirection: 'row', alignItems: 'center', marginTop: 8 },
  mutedText: { color: '#666', fontSize: 12 },

  adStats: { flexDirection: 'row', gap: 16, marginTop: 8 },
  adStat: { alignItems: 'center' },
  adStatValue: { fontSize: 18, fontWeight: '700', color: '#4a6fdc' },
  adStatLabel: { fontSize: 11, color: '#666', marginTop: 2 },

  adSectionTitle: { fontSize: 15, fontWeight: '700', color: '#333', marginBottom: 6 },
  adSectionContent: { fontSize: 14, color: '#555', lineHeight: 20 },
  adTags: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  adTag: { paddingHorizontal: 10, paddingVertical: 4, backgroundColor: '#e7f1ff', borderRadius: 15 },

  adPeriod: {
    backgroundColor: '#f8f9fa',
    padding: 12,
    borderRadius: 8,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  adPeriodInfo: { fontSize: 13, color: '#666' },

  adActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  adActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 8,
    flex: 1,
  },

  // 대시보드 공통 섹션 스타일
  dashboardSection: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 2 },
  },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
  uploadBtn: { backgroundColor: '#4a6fdc', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 6 },
  uploadBtnText: { color: '#fff', fontSize: 12, fontWeight: '700' },

  documentList: { gap: 8 },
  documentItem: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#fff', borderWidth: 1, borderColor: '#e0e0e0', borderRadius: 6, padding: 10 },
  documentInfo: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  documentIcon: { width: 32, height: 32, backgroundColor: '#f0f0f0', borderRadius: 6, alignItems: 'center', justifyContent: 'center', marginRight: 10 },
  documentDetails: { flex: 1 },
  documentName: { fontSize: 14, fontWeight: '600', color: '#333' },
  documentMeta: { fontSize: 11, color: '#999' },
  documentActions: { flexDirection: 'row', gap: 8 },
  documentActionBtn: { paddingHorizontal: 8, paddingVertical: 6, borderRadius: 4 },
  noDocuments: { padding: 16, alignItems: 'center' },

  // 리뷰 카드
  reviewCard: { backgroundColor: '#fff', borderRadius: 10, padding: 16, marginBottom: 10, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 5, shadowOffset: { width: 0, height: 2 } },
  reviewHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 },
  reviewerInfo: { flexDirection: 'row', alignItems: 'center' },
  reviewerAvatar: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#f0f0f0', alignItems: 'center', justifyContent: 'center', marginRight: 10 },
  reviewerName: { fontWeight: '700', fontSize: 14 },
  reviewCompany: { fontSize: 12, color: '#666' },
  reviewRating: { color: '#ffc107', fontSize: 14 },
  reviewContent: { fontSize: 14, color: '#555', lineHeight: 20, marginBottom: 8 },
  reviewDate: { fontSize: 12, color: '#999', textAlign: 'right' },

  // 모달
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', alignItems: 'center', justifyContent: 'center' },
  modalContent: { width: '90%', maxWidth: 500, backgroundColor: '#fff', borderRadius: 10, padding: 16 },
  modalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
  modalTitle: { fontSize: 16, fontWeight: '700' },
  modalFooter: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, marginTop: 12 },

  // 버튼 공통
  btn: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 6 },
  btnText: { color: '#fff', fontWeight: '700' },
  btnPrimary: { backgroundColor: '#4a6fdc' },
  btnSecondary: { backgroundColor: '#6c757d' },
  });