import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8f9fa' },
  header: {
    height: Platform.OS === 'ios' ? 56 : 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  headerLeft: { fontSize: 20 },
  headerRight: { fontSize: 20 },
  headerTitle: { fontSize: 16, fontWeight: '600' },
  actionsTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 16 },
  pageTitle: { fontSize: 20, fontWeight: '700' },
  primaryBtn: { backgroundColor: '#4a6fdc', padding: 10, borderRadius: 8 },
  primaryBtnText: { color: '#fff', fontWeight: '600' },
  jobCard: { backgroundColor: '#fff', borderRadius: 10, padding: 16, marginBottom: 12, shadowColor: '#000', shadowOpacity: 0.04, elevation: 1 },
  jobHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  jobTitle: { fontSize: 16, fontWeight: '700', marginBottom: 4 },
  jobCompany: { fontSize: 13, color: '#666' },
  jobStatus: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 16 },
  statusActive: { backgroundColor: '#e7f5ff' },
  statusClosed: { backgroundColor: '#fff5f5' },
  statusText: { color: '#333', fontWeight: '600' },
  jobStats: { flexDirection: 'row', gap: 12, marginTop: 10, justifyContent: 'space-between' },
  statText: { fontSize: 13, color: '#666' },
  jobFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 12 },
  postedDate: { fontSize: 12, color: '#999' },
  actionsRow: { flexDirection: 'row', gap: 8 },
  smallBtn: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 6, marginLeft: 6 },
  viewBtn: { backgroundColor: '#4a6fdc' },
  editBtn: { backgroundColor: '#f59f00' },
  deleteBtn: { backgroundColor: '#e03131' },
  btnText: { color: '#fff', fontSize: 12 },
  emptyState: { alignItems: 'center', padding: 40 },
  emptyStateSmall: { alignItems: 'center', padding: 12 },
  modalContainer: { flex: 1, backgroundColor: '#f8f9fa' },
  detailHeaderBlock: { backgroundColor: '#fff', borderRadius: 10, padding: 16, marginBottom: 16 },
  detailTitle: { fontSize: 18, fontWeight: '700' },
  detailMeta: { color: '#666', marginTop: 6 },
  detailActions: { flexDirection: 'row', marginTop: 12, justifyContent: 'space-between' },
  actionBtn: { padding: 10, borderRadius: 8, backgroundColor: '#e0e0e0' },
  actionBtnText: { color: '#fff' },
  closeBtn: { backgroundColor: '#e03131' },
  repostBtn: { backgroundColor: '#51cf66' },
  applicantCard: { backgroundColor: '#fff', borderRadius: 10, padding: 12, marginBottom: 10, flexDirection: 'row', alignItems: 'center' },
  avatarPlaceholder: { width: 50, height: 50, borderRadius: 25, backgroundColor: '#f0f0f0', alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  applicantName: { fontSize: 16, fontWeight: '700' },
  applicantDetails: { color: '#666' },
  statusBadge: { backgroundColor: '#4a6fdc', paddingHorizontal: 8, paddingVertical: 6, borderRadius: 8 },
  profileHeader: { backgroundColor: '#fff', borderRadius: 10, padding: 16, alignItems: 'center', marginBottom: 16 },
  profileAvatar: { width: 80, height: 80, borderRadius: 40, backgroundColor: '#f0f0f0', alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  profileName: { fontSize: 20, fontWeight: '700' },
  profileTitle: { color: '#666', marginBottom: 12 },
  profileSection: { backgroundColor: '#fff', borderRadius: 10, padding: 12, marginBottom: 12 },
  sectionTitle: { fontWeight: '700', marginBottom: 6 },
  sectionContent: { color: '#666', marginBottom: 4 },
  centeredOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', alignItems: 'center', justifyContent: 'center' },
  messageModalBox: { width: '90%', backgroundColor: '#fff', borderRadius: 10, padding: 12 },
  textarea: { minHeight: 100, borderWidth: 1, borderColor: '#ddd', borderRadius: 8, padding: 8, textAlignVertical: 'top', backgroundColor: '#fff' },
  toastBox: { position: 'absolute', left: '50%', transform: [{ translateX: -120 }], bottom: 80, backgroundColor: 'rgba(0,0,0,0.7)', padding: 10, borderRadius: 6, width: 240, alignItems: 'center' },
});
export default styles;