
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  backButton: {
    padding: 10,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#0066CC',
  },
  progressContainer: {
    padding: 20,
    backgroundColor: '#0066CC',
  },
  progressBackground: {
    height: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    marginBottom: 20,
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#2EBD59',
  },
  progressSteps: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  progressStep: {
    alignItems: 'center',
  },
  stepCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  stepCircleActive: {
    backgroundColor: '#fff',
  },
  stepText: {
    fontWeight: '600',
    color: '#0066CC',
  },
  stepLabel: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.8)',
    textAlign: 'center',
  },
  formContainer: {
    backgroundColor: '#fff',
    margin: 12,
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  formHeader: {
    alignItems: 'center',
    marginBottom: 30,
  },
  formTitle: {
    fontSize: 24,
    fontWeight: '600',
    marginBottom: 10,
    color: '#333',
  },
  formSubtitle: {
    color: '#666',
    fontSize: 14,
  },
  profileCompletion: {
    flexDirection: 'row',
    backgroundColor: 'rgba(0, 102, 204, 0.05)',
    borderRadius: 12,
    padding: 15,
    marginBottom: 20,
    alignItems: 'center',
  },
  completionText: {
    flex: 1,
  },
  completionTitle: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  completionTitleText: {
    fontWeight: '600',
    marginLeft: 8,
    color: '#333',
  },
  helpText: {
    fontSize: 12,
    color: '#666',
    marginBottom: 10,
  },
  completionBar: {
    height: 8,
    backgroundColor: '#F5F5F5',
    borderRadius: 4,
    overflow: 'hidden',
  },
  completionFill: {
    height: '100%',
    backgroundColor: '#0066CC',
  },
  completionPercentage: {
    fontSize: 20,
    fontWeight: '700',
    color: '#0066CC',
    marginLeft: 15,
  },
  formSection: {
    marginBottom: 30,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 10,
    borderBottomWidth: 2,
    borderBottomColor: '#eee',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    marginLeft: 10,
    color: '#333',
  },
  formGrid: {
    flexDirection: 'column',
  },
  formGroup: {
    width: '100%',
    marginBottom: 14,
  },
  fullWidth: {
    width: '100%',
  },
  label: {
    fontWeight: '500',
    marginBottom: 8,
    color: '#333',
  },
  required: {
    color: '#E74C3C',
  },
  input: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
  },
  textArea: {
    height: 100,
    textAlignVertical: 'top',
  },
  infoBox: {
    backgroundColor: 'rgba(0, 102, 204, 0.05)',
    borderLeftWidth: 4,
    borderLeftColor: '#0066CC',
    padding: 15,
    borderRadius: 0,
    marginBottom: 20,
  },
  infoBoxTitle: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  infoBoxTitleText: {
    fontWeight: '600',
    marginLeft: 8,
    color: '#333',
  },
  infoBoxContent: {
    fontSize: 14,
    color: '#666',
  },
  specialtyGroup: {
    marginBottom: 25,
  },
  specialtyLabel: {
    fontWeight: '500',
    marginBottom: 10,
    color: '#333',
  },
  specialtyContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  specialtyTag: {
    backgroundColor: '#F5F5F5',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 20,
  },
  specialtyTagSelected: {
    backgroundColor: '#0066CC',
    borderColor: '#0066CC',
  },
  specialtyTagText: {
    fontSize: 14,
    color: '#333',
  },
  specialtyTagTextSelected: {
    color: '#fff',
  },
  countryGroup: {
    marginBottom: 25,
  },
  countryLabel: {
    fontWeight: '500',
    marginBottom: 10,
    color: '#333',
  },
  countryContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  countryTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 20,
    gap: 5,
  },
  countryTagSelected: {
    backgroundColor: '#7B68EE',
    borderColor: '#7B68EE',
  },
  countryTagText: {
    fontSize: 14,
    color: '#333',
  },
  countryTagTextSelected: {
    color: '#fff',
  },
  experienceCards: {
    gap: 20,
  },
  experienceCard: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 12,
    padding: 20,
    position: 'relative',
  },
  removeBtn: {
    position: 'absolute',
    top: 15,
    right: 15,
    zIndex: 1,
  },
  experienceHeader: {
    marginBottom: 15,
  },
  experienceHeaderContent: {
    gap: 10,
  },
  experienceTitleInput: {
    fontWeight: '600',
    fontSize: 16,
    borderWidth: 0,
    padding: 0,
    marginBottom: 5,
  },
  experiencePeriodInput: {
    color: '#666',
    fontSize: 14,
    borderWidth: 0,
    padding: 0,
  },
  experienceCompanyInput: {
    color: '#666',
    fontSize: 14,
    borderWidth: 0,
    padding: 0,
    width: '100%',
    marginBottom: 10,
  },
  experienceDescriptionInput: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 6,
    padding: 10,
    fontSize: 14,
    minHeight: 60,
  },
  certificationCards: {
    gap: 20,
  },
  certificationCard: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 12,
    padding: 20,
    position: 'relative',
    backgroundColor: 'rgba(0, 102, 204, 0.02)',
  },
  certificationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  certificationNameInput: {
    fontWeight: '600',
    fontSize: 16,
    borderWidth: 0,
    padding: 0,
    flex: 1,
  },
  certificationStatusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  certificationStatus: {
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 20,
    fontSize: 12,
    fontWeight: '500',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    backgroundColor: '#fff',
  },
  certificationStatusText: {
    fontSize: 12,
    color: '#333',
  },
  certificationDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 15,
  },
  certDetailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    fontSize: 14,
  },
  certDetailInput: {
    borderWidth: 0,
    padding: 0,
    fontSize: 14,
    color: '#666',
  },
  fileUploadSection: {
    borderWidth: 2,
    borderColor: '#E0E0E0',
    borderStyle: 'dashed',
    borderRadius: 12,
    padding: 18,
    alignItems: 'center',
    marginBottom: 10,
  },
  fileUploadText: {
    color: '#666',
    marginVertical: 10,
  },
  fileUploadButton: {
    backgroundColor: '#0066CC',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 6,
  },
  fileUploadButtonText: {
    color: '#fff',
    fontWeight: '500',
  },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#E0E0E0',
    borderStyle: 'dashed',
    borderRadius: 8,
    padding: 12,
    gap: 10,
  },
  addButtonText: {
    color: '#666',
    fontWeight: '500',
  },
  formActions: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'stretch',
    marginTop: 20,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#eee',
    gap: 10,
  },
  secondaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    width: '100%',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    fontWeight: '500',
    color: '#333',
    marginLeft: 8,
  },
  buttonGroup: {
    flexDirection: 'column',
    gap: 10,
    width: '100%',
  },
  primaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0066CC',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    width: '100%',
    justifyContent: 'center',
  },
  primaryButtonText: {
    fontWeight: '500',
    color: '#fff',
    marginLeft: 8,
  },
});
