import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f7fa',
  },
  headerBox: {
    backgroundColor: '#fff',
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 16,
    padding: 20,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#2c3e50',
    marginBottom: 6,
  },
  headerDesc: {
    fontSize: 14,
    color: '#7f8c8d',
  },
  controls: {
    backgroundColor: '#fff',
    marginHorizontal: 16,
    marginBottom: 16,
    padding: 16,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 12,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  filterGroup: {
    flex: 1,
  },
  filterLabel: { fontWeight: '600', color: '#555', marginBottom: 8 },
  filterButtons: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  filterBtn: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 6,
    backgroundColor: '#fff',
  },
  filterBtnActive: { backgroundColor: '#e8f4fd', borderColor: '#86c5f4' },
  filterBtnText: { fontSize: 12, color: '#333' },
  filterBtnTextActive: { color: '#0066cc', fontWeight: '600' },
  searchInput: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 14,
  },
  btn: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 6,
  },
  btnText: { color: '#fff', fontSize: 14 },
  btnStrong: { fontWeight: '700' },
  btnPrimary: { backgroundColor: '#3498db' },
  btnDanger: { backgroundColor: '#e74c3c' },
  btnCancel: { backgroundColor: '#95a5a6', flex: 1, alignItems: 'center' },
  btnPayment: { backgroundColor: '#27ae60', flex: 2, alignItems: 'center' },
  btnSm: { paddingVertical: 6, paddingHorizontal: 12 },

  cartContainer: {
    marginHorizontal: 16,
    gap: 12,
  },
  cartItem: {
    backgroundColor: '#fff',
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 12,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  cartItemHeader: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#ecf0f1',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cartItemBody: {
    padding: 16,
    flexDirection: 'row',
    gap: 16,
  },
  itemCheckbox: { paddingTop: 5 },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 1,
    borderColor: '#bbb',
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  checkboxChecked: { backgroundColor: '#2ecc71', borderColor: '#27ae60' },
  checkboxMark: { color: '#fff', fontSize: 14, fontWeight: '700' },

  itemImage: {
    width: 120,
    height: 120,
    borderRadius: 8,
    backgroundColor: '#f8f9fa',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  itemDetails: { flex: 1 },
  itemTitle: { fontSize: 18, fontWeight: '700', marginBottom: 8, color: '#2c3e50' },
  itemDescription: { color: '#7f8c8d', fontSize: 14, marginBottom: 12 },
  itemMeta: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginBottom: 12 },
  metaItem: { flexDirection: 'row', alignItems: 'center', gap: 4, color: '#555' },
  itemPrice: { fontSize: 18, fontWeight: '700', color: '#3498db', marginBottom: 12 },
  itemActions: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  quantityControl: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: '#ddd', borderRadius: 6, overflow: 'hidden' },
  quantityBtn: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center', backgroundColor: '#f8f9fa' },
  quantityBtnText: { fontSize: 16, color: '#333' },
  quantityInput: { width: 50, height: 36, textAlign: 'center', borderLeftWidth: 1, borderRightWidth: 1, borderColor: '#ddd', fontSize: 14 },
  actionButtons: { flexDirection: 'row', gap: 8 },

  categoryBadge: { paddingVertical: 4, paddingHorizontal: 8, borderRadius: 4 },
  categoryBadgeText: { fontSize: 11, fontWeight: '600' },
  categoryPremium: { backgroundColor: '#e8f4fd' },
  categoryStandard: { backgroundColor: '#f0f0f0' },
  categoryBasic: { backgroundColor: '#fff8e1' },

  emptyCart: {
    alignItems: 'center',
    paddingVertical: 60,
    paddingHorizontal: 20,
    backgroundColor: '#fff',
    borderRadius: 12,
    marginHorizontal: 16,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  emptyCartIcon: { fontSize: 48, color: '#bdc3c7', marginBottom: 16 },
  emptyCartTitle: { fontSize: 20, fontWeight: '700', color: '#7f8c8d', marginBottom: 8 },
  emptyCartDescription: { color: '#95a5a6', marginBottom: 24 },

  bottomSheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#fff',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: -2 },
    elevation: 6,
  },
  bottomSheetHandle: { width: 40, height: 4, backgroundColor: '#ddd', borderRadius: 2, alignSelf: 'center', marginVertical: 8 },
  bottomSheetContent: { paddingHorizontal: 16, paddingBottom: 16 },
  sheetHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  sheetTitle: { fontSize: 18, fontWeight: '700', color: '#2c3e50' },
  sheetSummary: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
  summaryItem: { alignItems: 'flex-end' },
  summaryLabel: { fontSize: 14, color: '#7f8c8d', marginBottom: 4 },
  summaryValue: { fontSize: 16, fontWeight: '600', color: '#2c3e50' },
  summaryTotal: { fontSize: 20, color: '#3498db' },
  sheetActions: { flexDirection: 'row', gap: 12 },
});

// Export as a named export to match the import in ShoppingCartCorp.tsx
export { styles };