import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    paddingBottom: 24,
    backgroundColor: '#f5f6f8',
  },
  searchSection: {
    backgroundColor: '#fff',
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  searchTitle: {
    fontSize: 18,
    color: '#0066CC',
    marginBottom: 15,
  },
  searchBar: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 15,
  },
  searchInput: {
    flex: 1,
    padding: 12,
    borderWidth: 2,
    borderColor: '#e0e0e0',
    borderRadius: 8,
    fontSize: 14,
    backgroundColor: '#fff',
  },
  searchButton: {
    backgroundColor: '#0066CC',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 14,
  },
  filters: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#f0f0f0',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 20,
    fontSize: 12,
  },
  chipActive: {
    backgroundColor: '#0066CC',
    borderColor: '#0066CC',
  },
  chipText: {
    color: '#555',
    fontSize: 12,
  },
  chipTextActive: {
    color: '#fff',
  },
  bannerCarousel: {
    margin: 15,
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 15,
    elevation: 5,
    height: 180,
    position: 'relative',
  },
  bannerSlide: {
    width: width - 30, // Account for margins
    padding: 20,
    justifyContent: 'center',
    height: 180,
  },
  bannerSlide1: {
    backgroundColor: '#667eea',
  },
  bannerSlide2: {
    backgroundColor: '#f093fb',
  },
  bannerSlide3: {
    backgroundColor: '#4facfe',
  },
  bannerSlide4: {
    backgroundColor: '#43e97b',
  },
  bannerContent: {
    maxWidth: 300,
    alignItems: 'center',
    textAlign: 'center',
    alignSelf: 'center',
  },
  bannerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 10,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  bannerDesc: {
    fontSize: 14,
    color: '#fff',
    marginBottom: 15,
    opacity: 0.9,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  bannerButton: {
    padding: 10,
    paddingHorizontal: 20,
    backgroundColor: '#fff',
    borderRadius: 8,
    alignItems: 'center',
    alignSelf: 'center',
  },
  bannerButtonText: {
    color: '#333',
    fontWeight: '600',
    fontSize: 14,
  },
  bannerDots: {
    position: 'absolute',
    bottom: 15,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  bannerDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    marginHorizontal: 4,
  },
  bannerDotActive: {
    backgroundColor: '#fff',
    transform: [{ scale: 1.2 }],
  },
  tabNav: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 8,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
    margin: 15,
    marginBottom: 15,
  },
  tabButton: {
    flex: 1,
    padding: 12,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabButtonActive: {
    backgroundColor: '#0066CC',
  },
  tabButtonText: {
    color: '#666',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 4,
  },
  tabButtonTextActive: {
    color: '#fff',
  },
  tabContent: {
    paddingHorizontal: 15,
  },
  sectionTitle: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    marginTop: 15,
  },
  sectionTitleText: {
    marginLeft: 8,
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
  },
  urgentCard: {
    width: 280,
    backgroundColor: '#87CEEB',
    borderRadius: 12,
    padding: 15,
    marginRight: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    elevation: 5,
    position: 'relative',
    overflow: 'hidden',
    minHeight: 140,
  },
  cardBadge: {
    display: 'inline-block',
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    color: '#333',
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 12,
    fontSize: 11,
    fontWeight: '600',
    marginBottom: 10,
    overflow: 'hidden',
    alignSelf: 'flex-start',
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
    color: '#333',
    lineHeight: 1.3,
    textShadowColor: 'rgba(255, 255, 255, 0.8)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  cardCompany: {
    fontSize: 12,
    color: '#555',
    marginBottom: 10,
    textShadowColor: 'rgba(255, 255, 255, 0.8)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  cardPrice: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#0066CC',
  },
  cardDeadline: {
    fontSize: 12,
    color: '#999',
  },
  jobCard: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
    transition: 'transform 0.2s, box-shadow 0.2s',
    marginVertical: 6,
    marginHorizontal: 6,
    padding: 15,
  },
  jobBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    backgroundColor: '#2EBD59',
    marginBottom: 8,
  },
  jobBadgeNew: { backgroundColor: '#FF8C42' },
  jobBadgeHot: { backgroundColor: '#E74C3C' },
  jobBadgeText: {
    fontSize: 11,
    color: '#fff',
    fontWeight: 'bold'
  },
  jobTitle: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 6,
    color: '#333',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  jobCompany: {
    fontSize: 12,
    color: '#666',
    marginBottom: 10
  },
  tagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 5,
    marginBottom: 10
  },
  tagChip: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: '#f0f0f0',
    borderRadius: 4,
  },
  tagText: {
    fontSize: 11,
    color: '#666'
  },
  noticeItem: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
    display: 'flex',
    flexDirection: 'row',
    gap: 15,
  },
  noticeIcon: {
    width: 50,
    height: 50,
    borderRadius: 8,
    backgroundColor: '#0066CC',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  noticeIconGradient1: {
    backgroundColor: '#f093fb',
  },
  noticeIconGradient2: {
    backgroundColor: '#4facfe',
  },
  noticeIconGradient3: {
    backgroundColor: '#fa709a',
  },
  noticeIconGradient4: {
    backgroundColor: '#667eea',
  },
  noticeIconGradient5: {
    backgroundColor: '#a8edea',
  },
  noticeContent: {
    flex: 1,
  },
  noticeTitle: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 6,
    color: '#333',
  },
  noticeDesc: {
    fontSize: 12,
    color: '#666',
    marginBottom: 6,
  },
  noticeMeta: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    fontSize: 11,
    color: '#999',
  },
  noticeCategory: {
    color: '#FF1744',
    fontWeight: '600',
  },
  noticeOrg: {
    color: '#999',
  },
  noticeDate: {
    color: '#999',
  },
  breakingNews: {
    color: '#FF1744',
    fontWeight: '600',
  },
  applicationDeadline: {
    color: '#E74C3C',
    fontWeight: '600',
  },
  urgentNotice: {
    color: '#E74C3C',
    fontWeight: '600',
  },
  industryNews: {
    color: '#2196F3',
    fontWeight: '600',
  },
  globalNews: {
    color: '#4CAF50',
    fontWeight: '600',
  },
  placeholder: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 24,
  },
  placeholderText: {
    color: '#777',
  },
  consultantCard: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
    marginVertical: 6,
    marginHorizontal: 6,
    padding: 15,
  },
  consultantHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  consultantName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginLeft: 8,
  },
  consultantTitle: {
    color: '#666',
    marginTop: 2,
    fontSize: 12,
  },
  expertiseRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 5,
    marginBottom: 10,
  },
  expertiseChip: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: '#f0f0f0',
    borderRadius: 4,
  },
  expertiseText: {
    fontSize: 11,
    color: '#666',
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  ratingText: {
    marginLeft: 4,
    color: '#444',
    fontSize: 12,
    fontWeight: '600',
  },
  ratingLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  recommendedSection: {
    marginBottom: 20,
  },
  recommendedCard: {
    flex: 0,
    minWidth: 280,
    minHeight: 170,
    backgroundColor: '#FFD700',
    color: '#333',
    borderRadius: 12,
    padding: 15,
    marginHorizontal: 15,
    marginRight: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    elevation: 5,
    position: 'relative',
    overflow: 'hidden',
  },
  recommendedBadge: {
    display: 'inline-block',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    color: '#333',
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 20,
    fontSize: 11,
    fontWeight: '600',
    marginBottom: 10,
    overflow: 'hidden',
    alignSelf: 'flex-start',
  },
  recommendedBadgeText: {
    color: '#333',
    fontSize: 11,
    fontWeight: '600',
  },
  recommendedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  recommendedName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginLeft: 10,
  },
  recommendedTitle: {
    color: '#555',
    marginTop: 2,
    fontSize: 12,
  },
  recommendedExpertise: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 8,
    marginBottom: 10,
    gap: 6,
  },
  recommendedExpertiseChip: {
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    overflow: 'hidden',
  },
  recommendedExpertiseText: {
    fontSize: 12,
    color: '#333',
    fontWeight: '500',
  },
  recommendedRating: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  recommendedRatingLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  recommendedRatingText: {
    marginLeft: 4,
    color: '#333',
    fontSize: 12,
    fontWeight: '600',
  },
  recommendedLocation: {
    color: '#555',
    fontSize: 12,
  },

  recommendedEducationSection: {
    marginBottom: 20,
  },
  recommendedEducationCard: {
    flex: 0,
    minWidth: 300,
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    marginHorizontal: 15,
    marginRight: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  recommendedEducationBadge: {
    display: 'inline-block',
    paddingVertical: 4,
    paddingHorizontal: 8,
    backgroundColor: '#2EBD59',
    color: '#fff',
    borderRadius: 4,
    fontSize: 11,
    fontWeight: 'bold',
    marginBottom: 8,
    alignSelf: 'flex-start',
  },
  recommendedEducationBadgeText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: 'bold',
  },
  recommendedEducationTitle: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 6,
    color: '#333',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  recommendedEducationProvider: {
    fontSize: 12,
    color: '#666',
    marginBottom: 10,
  },
  recommendedEducationMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  recommendedEducationDuration: {
    color: '#555',
    fontSize: 12,
  },
  recommendedEducationPrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#0066CC',
  },
  recommendedEducationTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 5,
    marginBottom: 10,
  },
  recommendedEducationTagChip: {
    padding: 3,
    paddingHorizontal: 8,
    backgroundColor: '#f0f0f0',
    borderRadius: 4,
    fontSize: 11,
    color: '#666',
  },
  recommendedEducationTagText: {
    fontSize: 11,
    color: '#666',
  },
  recommendedEducationFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  recommendedEducationRating: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  recommendedEducationRatingText: {
    fontSize: 12,
    color: '#444',
  },
  recommendedEducationStudents: {
    color: '#666',
    fontSize: 12,
  },
  recommendedEducationLevel: {
    backgroundColor: '#fff3e0',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ffb74d',
  },
  recommendedEducationLevelText: {
    color: '#f57c00',
    fontSize: 11,
    fontWeight: '600',
  },

  eduCard: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
    marginVertical: 6,
    marginHorizontal: 6,
    padding: 15,
  },
  eduTitle: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 6,
    color: '#333',
  },
  eduProvider: {
    fontSize: 12,
    color: '#666',
    marginBottom: 10,
  },
  courseMetaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 4,
    marginBottom: 10,
  },
  courseTagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 5,
  },
  courseTagChip: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: '#f0f0f0',
    borderRadius: 4,
  },
  courseTagText: {
    fontSize: 11,
    color: '#666'
  },
});