import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    paddingBottom: 24,
    backgroundColor: '#fafafa',
  },
  searchSection: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 8,
  },
  searchTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#333',
    marginBottom: 12,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  searchInput: {
    flex: 1,
    height: 40,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    paddingHorizontal: 10,
    backgroundColor: '#fff',
  },
  searchButton: {
    marginLeft: 8,
    backgroundColor: '#2d89ef',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
  },
  searchButtonText: {
    color: '#fff',
    fontWeight: '600',
  },
  filters: {
    marginTop: 6,
  },
  chip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: '#eee',
    borderRadius: 16,
    marginRight: 8,
  },
  chipActive: {
    backgroundColor: '#2d89ef',
  },
  chipText: {
    color: '#555',
    fontSize: 13,
  },
  chipTextActive: {
    color: '#fff',
  },
  bannerCarousel: {
    width,
  },
  bannerSlide: {
    width,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  bannerContent: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  bannerTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 4,
  },
  bannerDesc: {
    color: '#555',
    marginBottom: 10,
  },
  bannerButton: {
    backgroundColor: '#2d89ef',
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  bannerButtonText: {
    color: '#fff',
    fontWeight: '600',
  },
  tabNav: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  tabButton: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 6,
    margin: 4,
    backgroundColor: '#fff',
  },
  tabButtonActive: {
    backgroundColor: '#2d89ef',
    borderColor: '#2d89ef',
  },
  tabButtonText: {
    marginLeft: 6,
    color: '#333',
    fontSize: 13,
  },
  tabButtonTextActive: {
    color: '#fff',
  },
  tabContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  sectionTitle: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  sectionTitleText: {
    marginLeft: 8,
    fontSize: 16,
    fontWeight: '700',
    color: '#d32f2f',
  },
  urgentCard: {
    width: 240,
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 12,
    marginRight: 10,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  jobCard: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 12,
    marginVertical: 8,
    marginHorizontal: 6,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  jobBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
    backgroundColor: '#eee',
    marginBottom: 6,
  },
  jobBadgeNew: { backgroundColor: '#e3f2fd' },
  jobBadgeHot: { backgroundColor: '#fdecea' },
  jobBadgeText: { fontSize: 12, color: '#333', fontWeight: '700' },
  jobTitle: { fontSize: 14, fontWeight: '700', marginBottom: 4 },
  jobCompany: { color: '#666', marginBottom: 8 },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 8 },
  tagChip: { backgroundColor: '#f5f5f5', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 10, marginRight: 6, marginBottom: 6 },
  tagText: { fontSize: 12, color: '#555' },
  cardBadge: {
    color: '#d32f2f',
    fontWeight: '700',
    marginBottom: 6,
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 4,
  },
  cardCompany: {
    color: '#666',
    marginBottom: 8,
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cardPrice: {
    fontWeight: '700',
  },
  cardDeadline: {
    color: '#666',
  },
  placeholder: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 24,
  },
  placeholderText: {
    color: '#777',
  },
  bannerDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 6,
  },
  bannerDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ddd',
    marginHorizontal: 4,
  },
  bannerDotActive: {
    backgroundColor: '#2d89ef',
  },
  consultantCard: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 12,
    marginVertical: 6,
    marginHorizontal: 6,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  consultantHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 6 },
  consultantName: { fontSize: 14, fontWeight: '700', color: '#333' },
  consultantTitle: { color: '#666', marginTop: 2 },
  expertiseRow: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 6 },
  expertiseChip: { backgroundColor: '#f5f5f5', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 10, marginRight: 6, marginBottom: 6 },
  expertiseText: { fontSize: 12, color: '#555' },
  ratingRow: { flexDirection: 'row', alignItems: 'center', marginTop: 6 },
  ratingText: { marginLeft: 6, color: '#444', fontSize: 12 },

  eduCard: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 12,
    marginVertical: 6,
    marginHorizontal: 6,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  eduTitle: { fontSize: 14, fontWeight: '700', marginBottom: 4 },
  eduProvider: { color: '#666', marginBottom: 6 },
  courseMetaRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 4 },
  courseTagRow: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 6 },
  courseTagChip: { backgroundColor: '#f5f5f5', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 10, marginRight: 6, marginBottom: 6 },
  courseTagText: { fontSize: 12, color: '#555' },

  noticeItem: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 12,
    marginVertical: 6,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  noticeTitle: { fontSize: 14, fontWeight: '700', marginBottom: 4 },
  noticeMeta: { flexDirection: 'row', justifyContent: 'space-between' },
  noticeCategory: { color: '#d32f2f', fontWeight: '700' },
  noticeDate: { color: '#666' },
});